apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: coturn
  labels:
    io.openvidu.service: coturn
  name: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openvidu.service: coturn
  strategy: {}
  template:
    metadata:
      annotations:
        app: conturn
      labels:
        io.openvidu.service: coturn
    spec:
      serviceAccount: openvidu 
      serviceAccountName: openvidu
      containers:
        - args:
            - --log-file=stdout
            - --listening-port=3478
            - --external-ip=${TURNIP}
            - --listening-ip=0.0.0.0
            - --no-tls
            - --no-dtls
            - --fingerprint
            - --lt-cred-mech
            - --min-port=57001
            - --max-port=57011
            - --realm=openvidu-openvidu.$BASE_DOMAIN
            - --user=${OPENVIDU_USERNAME}:${OPENVIDU_SERVER_SECRET}
            - --verbose
          env:
            - name: DB_NAME
              value: "0"
            - name: DB_PASSWORD
              value: ${OPENVIDU_SERVER_SECRET} 
            - name: REDIS_IP
              value: redis 
          image: openvidu/openvidu-coturn:6.0.0
          name: coturn
          ports:
            - containerPort: 3478
              name: udp-3478
              protocol: UDP 
            {{- range seq 0 10}}
            - containerPort: {{add 57001 .}}
              name: udp-{{add 57001 .}}
              protocol: UDP
            {{- end }}
      restartPolicy: Always
